---
- name: Delete Cloud VPN - Customized
  hosts: hub
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    junos_user: "root"
    junos_password: "TURdj5mplsvpn!"
    build_dir: "/tmp/"
    interfaces: [
      {'interface': 'st0', 'unit': '{{minion_id}}', 'family': 'inet', 'addr_type': 'address', 'addr': '10.66.{{minion_id}}.254/24', 
      'zone':'vpn', 'hit_protocols': ['all'], 'hit_services': ['all']} ]
    ike: [ 
      {'ike_name': 'ike-vpn-{{minion_id}}', 'ike_policy_name': 'ike-policy-{{minion_id}}', 
      'ike_policy_proposal': 'ike-proposal-{{minion_id}}'} ]
    ipsec: [ 
      {'ipsec_policy_name': 'vpn-policy-{{minion_id}}', 'ipsec_policy_proposal': 'ipsec-proposal-{{minion_id}}', 
      'ipsec_vpn_name': 'ipsec-vpn-{{minion_id}}'} ]

  tasks:
    - name: Build delete vpn tunnel interface
      template: src=templates/del_interfaces.set.j2 dest={{build_dir}}/del_interfaces.set
      with_items: '{{interfaces}}'

    - name: Apply delete vpn tunnel interface
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/del_interfaces.set overwrite=no logfile=logs/{{ inventory_hostname }}.log comment='Delete VPN tunnel interface'

    - name: Build delete vpn zone
      template: src=templates/del_interfaces_zone.set.j2 dest={{build_dir}}/del_interfaces_zone.set
      with_items: '{{interfaces}}'

    - name: Apply delete vpn zone
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/del_interfaces_zone.set overwrite=no logfile=logs/{{ inventory_hostname }}.log comment='Delete VPN zone'

    - name: Build delete VPN Phase 2
      template: src=templates/del_customize_vpn_ipsec.set.j2 dest={{build_dir}}/del_customize_vpn_ipsec.set
      with_items: '{{ipsec}}'

    - name: Apply delete VPN Phase 2
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/del_customize_vpn_ipsec.set overwrite=no logfile=logs/{{ inventory_hostname }}.log comment='Delete VPN Phase 2'

    - name: Build delete VPN Phase 1
      template: src=templates/del_customize_centor_vpn_ike.set.j2 dest={{build_dir}}/del_customize_centor_vpn_ike.set
      with_items: '{{ike}}'

    - name: Apply delete VPN Phase 1
      junos_install_config: host={{ inventory_hostname }} user={{ junos_user }} passwd={{ junos_password }} file={{ build_dir }}/del_customize_centor_vpn_ike.set overwrite=no logfile=logs/{{ inventory_hostname }}.log comment='Delete VPN Phase 1'

