---
- name: Configure DHCP
  hosts: vFW
  connection: local
  gather_facts: no
  roles:
    - Juniper.junos
  vars:
    junos_user: "root"
    junos_password: "TURdj5mplsvpn!"
    build_dir: "tmp/"
    dhcp: [ {'pool_name': '{{pool_name}}', 'subnet': '{{subnet}}', 'range_name': '{{range_name}}', 
    'low_addr': '{{low_addr}}', 'high_addr': '{{high_addr}}', 'name_server': '{{name_server}}', 'router': '{{router}}'} ]


  tasks:
    - name: set dhcp
      template: src=templates/dhcp.set.j2 dest={{build_dir}}/dhcp.set
      with_items: '{{dhcp}}'

    - name: Apply dhcp
      junos_install_config: 
        host={{ inventory_hostname }} 
        user={{ junos_user }} 
        passwd={{ junos_password }} 
        file={{ build_dir }}/dhcp.set 
        overwrite=no 
        logfile=logs/{{ inventory_hostname }}.log
        comment='Apply DHCP'
